### ISSUE TITLE
This extension violates the Chrome Web Store policy

### ISSUE THREAD

**Issue by Emrio** [webalorn/zestes-de-france-ioi#15]
L'extension a été retirée du Chrome Web Store pour violation des conditions du store.
Mon navigateur me conseille de la désinstaller.
Que s'est-il passé ? Est-ce que l'extension est sûre ?

**Comment by webalorn** [comment]
Salut, l'extension a été retirée des stores chrome & firefox, car je ne l'ai pas mise à jour depuis des années (simplement je n'utilise plus vraiment france-IOI), et il y a des nouveaux modes de fonctionnement auquel il faudrait explicitement adapter le code.
Mais l'extension n'a pas de problème en soi, elle n'a pas changé, tu peux toujours l'installer depuis la source si besoin, ou la garder si elle est déjà installée.

**Comment by Emrio** [comment]
Ok je vois. Ça me surprend un peu que le message pour "on a fait du housekeeping" est "cette extension viole nos CGU". Je pensais a priori que l'extension s'était peut-être fait hijack ^^'
